from flask import Flask, jsonify, request
from flask_cors import CORS
from dotenv import load_dotenv
import os
import openai
from flask_mail import Mail, Message

# Load environment variables from .env file
load_dotenv()

app = Flask(__name__)
CORS(app)

# Get OpenAI API key from environment variable
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
if not OPENAI_API_KEY:
    raise ValueError("OpenAI API key not found. Please set OPENAI_API_KEY in .env file")

# Configure OpenAI
openai.api_key = OPENAI_API_KEY

# Email configuration
app.config['MAIL_SERVER'] = 'smtp.gmail.com'
app.config['MAIL_PORT'] = 587
app.config['MAIL_USE_TLS'] = True
app.config['MAIL_USERNAME'] = 'ai@dengun.com'
app.config['MAIL_PASSWORD'] = 'hrnp phmk dsft wpbz'
app.config['MAIL_DEFAULT_SENDER'] = 'Dengun Assistant <ai@dengun.com>'

mail = Mail(app)

@app.route('/')
def root():
    return jsonify({"message": "AI Assistant API is running"})

@app.route('/health')
def health_check():
    return jsonify({"status": "healthy"})

@app.route('/api/chat', methods=['POST'])
def chat():
    try:
        data = request.json
        response = openai.ChatCompletion.create(
            model=data.get('model', 'gpt-3.5-turbo'),
            messages=data.get('messages', []),
            temperature=data.get('temperature', 0.7),
            max_tokens=data.get('max_tokens', 1000)
        )
        return jsonify(response)
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route("/api/send-email", methods=['POST'])
def send_email():
    try:
        data = request.get_json()
        to = data.get('to')
        subject = data.get('subject')
        content = data.get('content')
        user_name = data.get('userName', 'Not provided')
        user_email = data.get('userEmail', 'Not provided')
        user_phone = data.get('userPhone', 'Not provided')

        if not all([to, subject, content]):
            return jsonify({
                "error": "Missing required fields: to, subject, and content are required"
            }), 400

        html_content = f"""
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h2 style="color: #4a4a4a;">New Contact Information from Chat</h2>
            
            <div style="background-color: #f8f9fa; padding: 15px; border-radius: 5px; margin-bottom: 20px;">
                <h3 style="color: #2c3e50; margin-top: 0;">User Details</h3>
                <p><strong>Name:</strong> {user_name}</p>
                <p><strong>Email:</strong> {user_email}</p>
                <p><strong>Phone:</strong> {user_phone}</p>
            </div>
            
            <div>
                <h3 style="color: #2c3e50;">Conversation History</h3>
                <div style="white-space: pre-line;">{content}</div>
            </div>
            
            <p style="margin-top: 30px; font-size: 12px; color: #7f8c8d;">
                This email was automatically generated by Dengun Assistant.
            </p>
        </div>
        """

        msg = Message(
            subject=subject,
            recipients=[to],
            html=html_content
        )
        mail.send(msg)

        return jsonify({
            "message": "Email sent successfully"
        }), 200

    except Exception as e:
        return jsonify({
            "error": f"Failed to send email: {str(e)}"
        }), 500

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8000, debug=True) 